server:
  port: 8081
spring:
  application:
    name: "BoxProject"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: mongodb+srv://alvivasbancolombiacomco:angel.1994@cluster0.udlcnzl.mongodb.net/banking
  rabbitmq:
    addresses: "amqp://guest:guest@localhost:5672"
    virtual-host: "com.angel.javareactiva"
#    ssl:
#      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
